#!/usr/bin/env python3
"""
Add PostHog to every presentations/*/presentation Vite project.

Writes src/analytics.ts, adds the posthog-js dependency, and adds a
single side-effect import to src/main.tsx.

The presentation entry index.html is NOT touched: the build overwrites
it with cp dist/index.html index.html.

Usage:
    python3 scripts/add_posthog_presentations.py --test
    python3 scripts/add_posthog_presentations.py
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import posthog_config as cfg

POSTHOG_KEY = cfg.POSTHOG_KEY
API_HOST = cfg.API_HOST
SDK_DEFAULTS = cfg.SDK_DEFAULTS
SCRIPT_ID = cfg.SCRIPT_MARKER
TRIGGER_EVENTS = cfg.TRIGGER_EVENTS
LOAD_DELAY_MS = cfg.LOAD_DELAY_MS
MAX_QUEUE = cfg.MAX_QUEUE

PRESENTATIONS_DIR = cfg.PRESENTATIONS_DIR

POSTHOG_JS_VERSION = "^1.421.0"

ANALYTICS_TS_TEMPLATE = """// PostHog — generated by scripts/add_posthog_presentations.py
// Lazy load on first interaction or {delay}ms. Mirrors the loader in
// scripts/add_posthog.py so the static site and the decks behave alike.

const API_HOST = "{api_host}";
const PROJECT_KEY = "{key}";
const DEFAULTS = "{defaults}";
const LOAD_DELAY_MS = {delay};
const MAX_QUEUE = {max_queue};
const TRIGGER_EVENTS = {events};

type PostHogClient = {{
  init: (key: string, config: Record<string, unknown>) => void;
  capture: (name: string, properties?: Record<string, unknown>) => void;
}};

type WindowWithAnalytics = Window & {{
  posthog?: PostHogClient;
  gtag?: (...args: unknown[]) => void;
}};

const win = window as WindowWithAnalytics;
const queue: Array<[string, Record<string, unknown>]> = [];
let loaded = false;
let injected = false;

function client(): PostHogClient | null {{
  const c = win.posthog;
  return c !== undefined && typeof c.capture === "function" ? c : null;
}}

function enqueue(name: string, props: Record<string, unknown>): void {{
  if (loaded) {{
    const c = client();
    if (c !== null) c.capture(name, props);
    return;
  }}
  if (queue.length < MAX_QUEUE) queue.push([name, props]);
}}

function flush(): void {{
  const c = client();
  if (!loaded || c === null) return;
  while (queue.length > 0) {{
    const item = queue.shift();
    if (item !== undefined) c.capture(item[0], item[1]);
  }}
}}

function start(): void {{
  if (injected) return;
  injected = true;
  const s = document.createElement("script");
  s.id = "{script_id}";
  s.type = "text/javascript";
  s.crossOrigin = "anonymous";
  s.async = true;
  s.src = API_HOST.replace(".i.posthog.com", "-assets.i.posthog.com") + "/static/array.js";
  s.onload = () => {{
    const c = client();
    if (c === null) return;
    c.init(PROJECT_KEY, {{
      api_host: API_HOST,
      defaults: DEFAULTS,
      capture_pageview: false,
      autocapture: true,
    }});
    loaded = true;
    c.capture("$pageview", {{
      $current_url: window.location.href,
      $referrer: document.referrer,
    }});
    flush();
  }};
  document.head.appendChild(s);
}}

// Bridge the deck's existing gtag('event', ...) calls into PostHog.
function bridgeGtag(): void {{
  const original = win.gtag;
  if (typeof original !== "function") return;
  win.gtag = (...args: unknown[]): void => {{
    original(...args);
    if (args[0] !== "event" || typeof args[1] !== "string") return;
    const params = (args[2] ?? {{}}) as Record<string, unknown>;
    const props: Record<string, unknown> = {{}};
    if (params.event_category !== undefined) props.category = params.event_category;
    if (params.event_label !== undefined) props.label = params.event_label;
    if (params.value !== undefined) props.value = params.value;
    if (params.non_interaction !== undefined) props.non_interaction = params.non_interaction;
    enqueue(args[1], props);
    if (!loaded) start();
  }};
}}

function onFirstInteraction(): void {{
  start();
  for (const name of TRIGGER_EVENTS) {{
    document.removeEventListener(name, onFirstInteraction, true);
  }}
}}

bridgeGtag();
for (const name of TRIGGER_EVENTS) {{
  document.addEventListener(name, onFirstInteraction, {{ capture: true, passive: true }});
}}
window.setTimeout(start, LOAD_DELAY_MS);
"""

MAIN_TSX_IMPORT = 'import "./analytics";'


def render_analytics_ts() -> str:
    """Build the analytics module source."""
    return ANALYTICS_TS_TEMPLATE.format(
        delay=LOAD_DELAY_MS,
        api_host=API_HOST,
        key=POSTHOG_KEY,
        defaults=SDK_DEFAULTS,
        max_queue=MAX_QUEUE,
        events=json.dumps(TRIGGER_EVENTS),
        script_id=SCRIPT_ID,
    )


def add_dependency(pkg: dict):
    """Return (new_pkg, changed). Adds posthog-js to dependencies."""
    deps = pkg.setdefault("dependencies", {})
    if "posthog-js" in deps:
        return pkg, False
    deps["posthog-js"] = POSTHOG_JS_VERSION
    return pkg, True


def patch_main_tsx(src: str):
    """Return (new_src, changed). Adds the side-effect import after App."""
    if MAIN_TSX_IMPORT in src:
        return src, False
    anchor = 'import App from "./App";'
    if anchor not in src:
        return src, False
    return src.replace(anchor, f"{anchor}\n{MAIN_TSX_IMPORT}", 1), True


def collect_projects(presentations_dir: Path):
    """Every presentations/<slug>/presentation directory containing package.json."""
    found = []
    for child in sorted(presentations_dir.iterdir()):
        if not child.is_dir():
            continue
        project = child / "presentation"
        if (project / "package.json").exists():
            found.append(project)
    return found


def process(projects):
    """Apply all three edits. Returns a stats dict."""
    stats = {"projects": len(projects), "deps": 0, "modules": 0, "main": 0, "errors": 0}
    module_src = render_analytics_ts()
    dry_run = "--test" in sys.argv

    for project in projects:
        name = project.parent.name
        try:
            pkg_path = project / "package.json"
            pkg = json.loads(pkg_path.read_text(encoding="utf-8"))
            new_pkg, dep_changed = add_dependency(pkg)
            if dep_changed:
                stats["deps"] += 1
                if not dry_run:
                    pkg_path.write_text(
                        json.dumps(new_pkg, indent=2, ensure_ascii=False) + "\n",
                        encoding="utf-8",
                    )

            analytics_path = project / "src" / "analytics.ts"
            if not analytics_path.exists():
                stats["modules"] += 1
                if not dry_run:
                    analytics_path.write_text(module_src, encoding="utf-8")

            main_path = project / "src" / "main.tsx"
            main_src = main_path.read_text(encoding="utf-8")
            new_src, main_changed = patch_main_tsx(main_src)
            if main_changed:
                stats["main"] += 1
                if not dry_run:
                    main_path.write_text(new_src, encoding="utf-8")

            changed = dep_changed or main_changed or not analytics_path.exists()
            print(f"  {'patch ' if changed else 'skip  '} {name}")
        except (OSError, ValueError, KeyError) as exc:
            print(f"  ERROR {name}: {exc}")
            stats["errors"] += 1

    return stats


def main():
    projects = collect_projects(PRESENTATIONS_DIR)
    mode = "DRY RUN (pass no --test to write)" if "--test" in sys.argv else "WRITE"
    print(f"add_posthog_presentations.py — {len(projects)} projects — {mode}\n")
    stats = process(projects)
    print(
        f"\nprojects={stats['projects']} deps={stats['deps']} "
        f"modules={stats['modules']} main={stats['main']} errors={stats['errors']}"
    )
    if stats["errors"]:
        sys.exit(1)


if __name__ == "__main__":
    main()
