// PostHog — generated by scripts/add_posthog_presentations.py
// Lazy load on first interaction or 3000ms. Mirrors the loader in
// scripts/add_posthog.py so the static site and the decks behave alike.

const API_HOST = "https://us.i.posthog.com";
const PROJECT_KEY = "phc_Bh9JEckmeRh3GGbBNyV45tj44L6NqxmeBqAxRPRtdzK5";
const DEFAULTS = "2026-05-30";
const LOAD_DELAY_MS = 3000;
const MAX_QUEUE = 50;
const TRIGGER_EVENTS = ["touchstart", "click", "scroll", "keydown", "mouseover"];

type PostHogClient = {
  init: (key: string, config: Record<string, unknown>) => void;
  capture: (name: string, properties?: Record<string, unknown>) => void;
};

type WindowWithAnalytics = Window & {
  posthog?: PostHogClient;
  gtag?: (...args: unknown[]) => void;
};

const win = window as WindowWithAnalytics;
const queue: Array<[string, Record<string, unknown>]> = [];
let loaded = false;
let injected = false;

function client(): PostHogClient | null {
  const c = win.posthog;
  return c !== undefined && typeof c.capture === "function" ? c : null;
}

function enqueue(name: string, props: Record<string, unknown>): void {
  if (loaded) {
    const c = client();
    if (c !== null) c.capture(name, props);
    return;
  }
  if (queue.length < MAX_QUEUE) queue.push([name, props]);
}

function flush(): void {
  const c = client();
  if (!loaded || c === null) return;
  while (queue.length > 0) {
    const item = queue.shift();
    if (item !== undefined) c.capture(item[0], item[1]);
  }
}

function start(): void {
  if (injected) return;
  injected = true;
  const s = document.createElement("script");
  s.id = "myo-posthog-script";
  s.type = "text/javascript";
  s.crossOrigin = "anonymous";
  s.async = true;
  s.src = API_HOST.replace(".i.posthog.com", "-assets.i.posthog.com") + "/static/array.js";
  s.onload = () => {
    const c = client();
    if (c === null) return;
    c.init(PROJECT_KEY, {
      api_host: API_HOST,
      defaults: DEFAULTS,
      capture_pageview: false,
      autocapture: true,
    });
    loaded = true;
    c.capture("$pageview", {
      $current_url: window.location.href,
      $referrer: document.referrer,
    });
    flush();
  };
  document.head.appendChild(s);
}

// Bridge the deck's existing gtag('event', ...) calls into PostHog.
function bridgeGtag(): void {
  const original = win.gtag;
  if (typeof original !== "function") return;
  win.gtag = (...args: unknown[]): void => {
    original(...args);
    if (args[0] !== "event" || typeof args[1] !== "string") return;
    const params = (args[2] ?? {}) as Record<string, unknown>;
    const props: Record<string, unknown> = {};
    if (params.event_category !== undefined) props.category = params.event_category;
    if (params.event_label !== undefined) props.label = params.event_label;
    if (params.value !== undefined) props.value = params.value;
    if (params.non_interaction !== undefined) props.non_interaction = params.non_interaction;
    enqueue(args[1], props);
    if (!loaded) start();
  };
}

function onFirstInteraction(): void {
  start();
  for (const name of TRIGGER_EVENTS) {
    document.removeEventListener(name, onFirstInteraction, true);
  }
}

bridgeGtag();
for (const name of TRIGGER_EVENTS) {
  document.addEventListener(name, onFirstInteraction, { capture: true, passive: true });
}
window.setTimeout(start, LOAD_DELAY_MS);
